# Generated by Django 5.1.6 on 2025-05-24 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='rest_framework_api_key.apikey')),
            ],
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
