# Generated by Django 5.1.6 on 2025-05-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appsettings_delete_settings'),
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppSettings',
            new_name='AppSetting',
        ),
    ]
