# Generated by Django 5.1.6 on 2025-05-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_addtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='addtransaction',
            name='category',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='addtransaction',
            name='type',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10),
        ),
    ]
