# Generated by Django 5.1.6 on 2025-05-24 20:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_addtransaction_amount_and_more'),
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtransaction',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rest_framework_api_key.apikey'),
        ),
        migrations.AlterField(
            model_name='addtransaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 24, 20, 40, 13, 342509)),
        ),
    ]
